services:
  api:
    image: opsmithe/myapp-api:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    image: opsmithe/myapp-worker:latest
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  frontend:
    image: opsmithe/myapp-frontend:latest
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://api:3000
      - NODE_ENV=development
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: myapp-network
